config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users,  only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, { presence: true }

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : '画像が投稿されてます'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :content, presence: true, unless: :image?
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  before_action :set_group

  def index
    # 送られてきたIDから最新のIDまでを取得させる
    @messages = @group.messages.includes(:user).where("id > ?", params[:id])
    respond_to do |format|
      format.json
    end
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:edit, :update]

  def index
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:notice] = "グループを作成しました"
      redirect_to action: :index
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      flash[:notice] = "グループを編集しました"
      redirect_to action: :index
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, { :user_ids => [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージが送信されました。" }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = "メッセージを入力してください。"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id)
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for group, html: { class: 'new_chat_group', id: 'new_chat_group' } do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        .chat-group-form__field--left
          - group.errors.full_messages.each do |message|
            %li= message

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :グループ名, class: 'chat-group-form__label', for: 'chat_group_name'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat-group-form__input', id: 'chat_group_name', placeholder: "グループ名を入力してください"

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバーを追加, class: 'chat-group-form__label', for: 'user-search-field'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input{ id: 'user-search-field' ,placeholder: "追加したいユーザー名を入力してください" }
      .user-search-result{ id: 'user-search-result' }

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :チャットメンバー, class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-users{id: 'chat-group-users'}
        .chat-group-user.clearfix{id: "chat-group-user-#{current_user.id}"}
          %input{ name: 'group[user_ids][]', type: 'hidden', value: "#{current_user.id}" }
          %p.chat-group-user__name
            = current_user.name
        - group.users.each do |user|
        - next if current_user.name == user.name
          .chat-group-user.clearfix{id: "chat-group-user-#{user.id}"}
            %input{ name: 'group[user_ids][]', type: 'hidden', value: "#{user.id}" }
            %p.chat-group-user__name
              = user.name
              .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn{ id: "chat-group-user-#{user.id}" }削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit 'Save', class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', group: @group

app/views/groups/index.html.haml
%header.header
.wrapper
  = render "messages/side_bar"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', group: @group

app/views/layouts/_flash.html.haml
- flash.each do |key, value|
  = content_tag :div, value, class: "flash flash__#{key}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/flash'
    = yield

app/views/messages/_message.html.haml
.message{ data: {id: "#{message.id}"}}
  .upper-info.clearfix
    %p.upper-info__user= message.user.name
    %p.upper-info__date= message.created_at.strftime('%Y/%m/%d(%a)%H:%M:%S')
  - if message.content.present?
    %p.message__text= message.content
  = image_tag message.image.url if message.image.present?

app/views/messages/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__box
      %p.side-header__box__user-name
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__edit-user
          = link_to new_group_path do
            %i.fa.fa-edit
        %li.side-header__box__menu__new-group
          = link_to edit_user_path(current_user.id) do
            %i.fa.fa-cog
  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group.id) do
        .group
          %p.group__group-name= group.name
          %p.group__latest-message= group.show_last_message

app/views/messages/index.html.haml
%header.header
.wrapper
  = render "messages/side_bar"
  .chat-main
    .main-header
      .main-header__left-box
        %h2.main-header__left-box__current-group= @group.name
        %ul.main-header__left-box__member-list
          Member :
          - @group.users.each do |user|
            %li.main-header__left-box__member-list__member= user.name
      / to do 選んだグループのチャット画面に遷移するようにする
      =link_to edit_group_path(@group) do
        .main-header__edit-btn Edit
    .messages
      = render @messages
    .form
      = form_for [@group, @message], html: { class: "new-message", id: "new-message" } do |f|
        .input-box
          = f.text_field :content, class: "input-box__text", placeholder: "type a message"
          %label.image-label{ for: "message_image" }
            %i.fa.fa-image
            = f.file_field :image, class: "image-label__input", id: "message_image"
        = f.submit "send", class: "new-message__submit-btn"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'